<a href="https://colab.research.google.com/github/LaetitiaVerel/Odyssey-Quests/blob/master/Numpy%20%3A%20Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy : Introduction

**Numpy allows you to manipulate data in the form of an array.**

**Perform the missions below with Numpy.**

In [ ]:
# Mission 1 : Show Numpy's version
import numpy as np
print(np.__version__)

1.18.2


In [ ]:
# Mission 2 : Create a Numpy array of length 3, filled with floats worth 0.x, x can take any value
import numpy as np
a = np.array([0.1, 0.3, 0.8])
print(a)


[0.1 0.3 0.8]


In [ ]:
# Mission 3 : Create a function that with the random.random() method will display 10 random variables strictly greater than 0.25
import numpy as np
import random
for i in range(10):
  attempt = 0
  while attempt < 0.25:
    attempt = random.random()*10 + 0.25
  print(attempt)


4.1262723625867945
6.28352250175195
7.101523922600085
9.520780114112302
4.942741932163177
1.3512678608789828
6.962934227571262
8.161069175164293
5.2581761367240984
2.738915222223733


In [ ]:
# Mission 4 : What does the np.empty() method do? You don't just have to copy the doc, but explain it in French
np.empty() est utilisée pour créer un nouveau tableau.

In [ ]:
# Mission 5 : Create an array filled with 7 zeros of float type
import numpy as np
b = np.array([0, 0, 0, 0, 0, 0, 0], float)
print(b)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Mission 6 : Create an array filled with 10 random digits of type int
import numpy as np
c = np.random.randint(1, 10, (1, 10))
print(c)

[[6 6 4 3 4 1 3 7 1 7]]


In [ ]:
# Mission 7 : Create an array that will contain 70 values randomly selected from the numbers: 0, 1, 2, 3, 4, 5, 6, 7.
d = np.random.randint(0, 8, (7, 10))
print(d)

[[5 7 6 4 4 6 5 1 0 3]
 [0 3 3 0 2 5 1 3 5 4]
 [3 4 4 2 2 2 2 6 4 2]
 [4 6 6 4 1 5 1 2 4 6]
 [6 5 4 6 6 0 2 7 6 4]
 [1 4 1 3 3 5 1 6 3 6]
 [4 1 3 2 6 0 6 2 3 6]]


In [ ]:
# Mission 8 : Uses the slicing operator to access items between position 3 and 6 inclusive of mission 6
import numpy as np
c = np.random.randint(1, 10, (1, 10))
print(c)
print(c[0][3:7])

[[1 8 1 6 3 5 7 1 2 1]]
[6 3 5 7]


In [ ]:
# Mission 9 : Uses a method to return the index of the minimum element of the array of mission 7
d = np.random.randint(0, 8, (7, 10))
print(d)
print(np.amin(d))

[[3 4 1 6 1 0 0 1 3 3]
 [0 7 4 5 1 1 6 0 7 4]
 [5 7 7 3 6 2 4 6 0 6]
 [7 3 4 0 0 6 2 2 3 1]
 [4 5 5 4 1 5 4 1 2 2]
 [6 7 2 0 3 2 2 3 6 2]
 [6 2 5 3 1 3 6 1 1 4]]
0


In [ ]:
# Mission 10 : Using a numpy method, returns the indexes of values greater than the median value of the array of mission 6
import numpy as np
c = np.random.randint(1, 10, (1, 10))
print(c)

e = np.median(c)
print(np.nonzero(c > e))

[[9 9 2 5 2 7 4 6 3 2]]
(array([0, 0, 0, 0, 0]), array([0, 1, 3, 5, 7]))


In [ ]:
# Mission 11: After creating 3 arrays filled with random int's, which you will place in an array
# Create a function that will go through the elements of the 3 arrays in turn.
# This will give : Element 1 of arrays 1, 2 and 3. Element 2 of array 1, 2 and 3...
import numpy as np
x = np.random.randint(0, 10,(1, 5))
y = np.random.randint(0, 10,(1, 5))
z = np.random.randint(0, 10,(1, 5))
f = [x, y, z]

print(f)

def function(f):
  for i in np.nditer(f):
    print(i)

function(f)

[array([[5, 0, 4, 1, 2]]), array([[5, 3, 3, 2, 7]]), array([[6, 0, 2, 9, 7]])]
(array(5), array(5), array(6))
(array(0), array(3), array(0))
(array(4), array(3), array(2))
(array(1), array(2), array(9))
(array(2), array(7), array(7))


In [ ]:
# Mission 12: Create an array and fill it with 20 float random values.
# Create a function that will browse the array and indicate the smallest and largest value in the array.
import numpy as np
g = np.random.random(20)
print(g)

def min_max(g):
  print("The smallest is :", g.min())
  print("The largest is :", g.max())

min_max(g)

[0.14573199 0.67755186 0.64694903 0.13899046 0.21979836 0.34012149
 0.11455237 0.362647   0.62415962 0.71113932 0.66955827 0.15361548
 0.28587046 0.13270846 0.1387401  0.50212547 0.07343159 0.37046469
 0.50132456 0.84204478]
The smallest is : 0.07343159419090761
The largest is : 0.842044778503912


In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int type values between 0 and 10.
# Create a function that will run through each array with a while loop.
# At each turn of the loop the function will compare the values of the 2 arrays located at the same position.
# in order to return the index to which the values of the 2 arrays are equal.
# If no value is equal to the same position in the 2 arrays, return the message: "No value in common".
h = np.random.randint(10, size = (2,20))
print(h)

def value_in_common(array):
  loop = 0
  while loop < 10:
    if array[0,loop] == array[1,loop]:
      print(loop)
    else:
      print("No value in commom")
    loop += 1

value_in_common(h)

[[6 5 6 6 3 0 6 0 5 2 0 5 5 1 2 3 3 7 2 4]
 [4 4 3 1 9 1 3 8 7 2 3 8 9 9 1 9 2 9 1 9]]
No value in commom
No value in commom
No value in commom
No value in commom
No value in commom
No value in commom
No value in commom
No value in commom
No value in commom
9
